### ISSUE TITLE
QUNEO transport controls mapped weirdly

### ISSUE THREAD

**Issue by danmackinlay** [dataf1ow/KMI_Bitwig_Scripts#1]
I don't know if this is a documentation problem or a bug. Perhaps I'm supposed to load up a particular preset to use this mapping? However, trying to  use this controller script with the default interface script produces unexpected results and weird controller behaviour.
Example: Transport controls. According to the QUNEO manual, the diamond, square and triangle transport controls on the top left are mapped to C0 (=24), C#0 (=25) and D0 (=26)

However, if i look t the MIDI listener, it's different notes, specifically: 29, 30 and 31
```js
function transportControl(status, data1, data2){
	if (data1 == 29 && data2 == 127){
		transport.record();
	}else if (data1 == 30 && data2 == 127){
		transport.stop();
	}else if (data1 == 31 && data2 == 127){
		transport.play();
	}
};
```

notes 25 and 26 are mapped in a different function, `scaleIndexScroll` and they appear to change  the octave of the pads.

I guess I can work through all this and manually change the numbers, but it seems unlikely that this controller would be systematically wrong; so perhaps the error is mine? Or do other people have this issue?

Am I, for example, using an incorrect preset? In which case I guess I need to know which preset to use to enable this controller, which is fine, but may I request a documentation update to make this clear?

Or am i using an outdated version? I checked out a fresh copy of this repository. However, @dataf1ow has another QUNEO repository - https://github.com/dataf1ow/QUNEO - but this looks a little older, so I presume I'm using the right one now?

**Comment by danmackinlay** [comment]
Ach! moments after I submitted this I found that the repository has a .quneoPreset file, which i presume is the correct one to use to get the controller working. Sorry!

I suggest that mentioning the existence of this preset in the .html help as well as in the repository README might save others some time ;-)

In the interim, perhaps this ticket will assist other confused people

**Comment by dataf1ow** [comment]
Did you look at the instructions/version notes in the documentation folder? There's mention of it there. I suppose I could put it in the readme/html file as well.
